config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inventories
  resources :guitars
  get 'home/tracker'
  root 'home#index'

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guitar.rb
class Guitar < ApplicationRecord
	belongs_to :user
end

app/models/inventory.rb
class Inventory < ApplicationRecord

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :guitars
          has_many :inventories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]
  
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /guitars or /guitars.json
  def index
    @guitars = Guitar.all
  end

  # GET /guitars/1 or /guitars/1.json
  def show
  end

  # GET /guitars/new
  def new
    # @guitar = Guitar.new
    @guitar = current_user.guitars.build
  end

  # GET /guitars/1/edit
  def edit
  end

  # POST /guitars or /guitars.json
  def create
    # @guitar = Guitar.new(guitar_params)
    @guitar = current_user.guitars.build(guitar_params)

    respond_to do |format|
      if @guitar.save
        format.html { redirect_to guitar_url(@guitar), notice: "Guitar was successfully created." }
        format.json { render :show, status: :created, location: @guitar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitars/1 or /guitars/1.json
  def update
    respond_to do |format|
      if @guitar.update(guitar_params)
        format.html { redirect_to guitar_url(@guitar), notice: "Guitar was successfully updated." }
        format.json { render :show, status: :ok, location: @guitar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitars/1 or /guitars/1.json
  def destroy
    @guitar.destroy!

    respond_to do |format|
      format.html { redirect_to guitars_url, notice: "Guitar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @guitar = current_user.guitars.find_by(id: params[:id])
    redirect_to guitars_path, notice: "Not Authorised To Edit This Guitar" if @guitar.nil?
    
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guitar
      @guitar = Guitar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guitar_params
      params.require(:guitar).permit(:link, :brand, :model, :body_type, :wood_type, :price, :condition, :offers, :nut_width, :bridge_type, :case_included, :comments, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tracker
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]

  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    # @inventory = Inventory.new
    @inventory = current_user.inventories.build
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    # @inventory = Inventory.new(inventory_params)
    @inventory = current_user.inventories.build(inventory_params)
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy!

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @inventory = current_user.inventories.find_by(id: params[:id])
    redirect_to inventories_path, notice: "Not Authorised To Edit This Guitar" if @inventory.nil?
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:brand, :model, :body_type, :wood_type, :finish, :price, :condition, :nut_width, :comments, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/guitars/_form.html.erb
<%= form_with(model: guitar) do |form| %>
  <% if guitar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guitar.errors.count, "error") %> prohibited this guitar from being saved:</h2>

      <ul>
        <% guitar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :link, style: "display: block; color: #D2691E" %>
    <%= form.text_field :link, class:"form-control", placeholder:"Paste listing link here" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :brand, style: "display: block; color: #D2691E" %>
    <%= form.text_field :brand, class:"form-control", placeholder:"Brand/luthier" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :model, style: "display: block; color: #D2691E" %>
    <%= form.text_field :model, class:"form-control", placeholder:"Guitar model" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :body_type, style: "display: block; color: #D2691E" %>
    <%= form.text_field :body_type, class:"form-control", placeholder:"Body type (e.g. solid, plywood)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :wood_type, style: "display: block; color: #D2691E" %>
    <%= form.text_field :wood_type, class:"form-control", placeholder:"Wood type" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :price, style: "display: block; color: #D2691E" %>
    <%= form.text_field :price, class:"form-control", placeholder:"Asking price" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :condition, style: "display: block; color: #D2691E" %>
    <%= form.text_field :condition, class:"form-control", placeholder:"Condition (e.g. New, Very Good, Fair/Used)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :offers, style: "display: block; color: #D2691E" %>
    <%= form.text_field :offers, class:"form-control" , placeholder:"Open to offers? (yes/no)"%>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :nut_width, style: "display: block; color: #D2691E" %>
    <%= form.text_field :nut_width, class:"form-control" , placeholder:"Nut width"%>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :case_included, style: "display: block; color: #D2691E" %>
    <%= form.text_field :case_included, class:"form-control", placeholder:"Case included? (yes/no)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :comments, style: "display: block; color: #D2691E" %>
    <%= form.text_field :comments, class:"form-control" , placeholder:"Extra comments"%>
  </div>
  <br>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :guitar_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/guitars/_guitar.html.erb
<div style="background-color: #343a40; border-radius: 24px; padding: 10px;"  id="<%= dom_id guitar %>">

  <p>
    <strong style="color: #D2691E;">Link:</strong>
    <div>
      <a style="font-size: 16px; border-radius: 24px; background-color: #D2691E; color: white; border-width: 2px; border-color: #D2691E; text-decoration: none; font-family: 'Century Gothic'; display: block; margin-left: 5px; margin-right: auto;" class="btn btn-primary" data-bs-toggle="collapse" href="#<%= dom_id guitar %>_content" role="button" aria-expanded="false" aria-controls="<%= dom_id guitar %>_content">
        Show Link
      </a>
    </div>
    <br>

    <div class="collapse" id="<%= dom_id guitar %>_content" style="color: #fff; max-width: 1000px; overflow-wrap: break-word; word-break: break-all;">
      <%= guitar.link %>
    </div>

  </p>

  <p>
    <strong style="color: #D2691E;">Brand:</strong>
    <span style="color: #fff;"><%= guitar.brand %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Brand:</strong>
    <span style="color: #fff;"><%= guitar.brand %></span>
  </p>

  <p>
    <strong style="color: #D2691E;">Model:</strong>
    <span style="color: #fff;"><%= guitar.model %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Body Type:</strong>
    <span style="color: #fff;"><%= guitar.body_type %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Wood Type:</strong>
    <span style="color: #fff;"><%= guitar.wood_type %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Price:</strong>
    £<span style="color: #fff;"><%= guitar.price %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Condition:</strong>
    <span style="color: #fff;"><%= guitar.condition %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Offers?:</strong>
    <span style="color: #fff;"><%= guitar.offers %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Nut width:</strong>
    <span style="color: #fff;"><%= guitar.nut_width %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Case included?:</strong>
    <span style="color: #fff;"><%= guitar.case_included %></span>
  </p>

  <p>
    <strong style="color: #D2691E";>Comments:</strong>
    <span style="color: #fff;"><%= guitar.comments %></span>
  </p>

</div>

app/views/guitars/edit.html.erb
<h1 style="color: #D2691E; font-family: Century Gothic;">Edit Guitar details</h1>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Back to guitars", guitars_path, class:"btn btn-secondary" %>
</div>

app/views/guitars/index.html.erb
<div class="d-flex align-items-center">
  <img src="/guitaricon.png" alt="Icon" width="150" height="150" style="vertical-align: ;">

  <h1 style="font-family: 'Century Gothic', sans-serif; font-size: 28px; font-weight: bold; text-align: center; margin-bottom: 20px; color: #D2691E;
    margin-left: 20px;  text-decoration: underline;">All Guitar Listings</h1>
</div>
<table class="table table-dark table-striped" style="border-collapse: collapse; border-radius: 10px; overflow: hidden; width: 100%; color: gray">
  <thead>
    <tr >
      <th>Link</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Body</th>
      <th>Wood</th>
      <th>Price</th>
      <th>Condition</th>
      <th>Offers</th>
      <th>Nut</th>
      <th>Case</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-group-divider" style="background-color: gray">
    <div id="guitars">
      <% @guitars.each do |guitar| %>
        <% if guitar.user == current_user %>
        <tr>
          <td><%= link_to "View Listing", guitar.link, target: "_blank" %></td>
          <td><%= guitar.brand %></td>
          <td><%= guitar.model %></td>
          <td><%= guitar.body_type %></td>
          <td><%= guitar.wood_type %></td>
          <td>£<%= guitar.price %></td>
          <td><%= guitar.condition %></td>
          <td><%= guitar.offers %></td>
          <td><%= guitar.nut_width %></td>
          <td><%= guitar.case_included %></td>
          <td><%= guitar.comments %></td>
          <td><%= link_to "Show Guitar", guitar %></td>
          <td><%= link_to "Edit", edit_guitar_path(guitar) %></td>
          <td><%= link_to 'Delete', guitar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    </div>
  </tbody>
<br>
<%= link_to "Add Guitar Listing", new_guitar_path, class:"btn btn-secondary", style: "display: block; margin: 0 auto; width: 200px; text-align: center; font-size: 16px; padding: 10px 20px; border-radius: 24px; background-color: #D2691E; color: white; border-width: 2px; border-color: #D2691E; text-decoration: none; font-family: 'Century Gothic'" %>
<br><br>

app/views/guitars/new.html.erb
<br>
<h1 style="font-family: 'Century Gothic'; color: #D2691E;"><u>Add Guitar to Listings</u></h1>
<br>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Back to Guitars", guitars_path %>
</div>

app/views/guitars/show.html.erb
<%= render @guitar %>

<div>
  <br>
  <%= link_to "Edit this Guitar", edit_guitar_path(@guitar), class:"btn btn-secondary" %> |
  <%= link_to "Back to Guitars", guitars_path, class:"btn btn-dark"  %>
  <br>

  <%= button_to "Destroy this Guitar", @guitar, method: :delete, class:"btn btn-danger" %>
</div>

<br>
 dev<br>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <img src="/logo.png" alt="Icon" width="50" height="50" style="margin-right: 20px;">
    <%= link_to 'Guitar Tracker', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Listings", guitars_path, class:"nav-link active" %>
        </li>

        <li class="nav-item">
          <%= link_to "Inventory", inventories_path, class:"nav-link active" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link active" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link active" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link active" %>
          </li>
        <% end %>
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-none btn search" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<style>
  /* Custom CSS for navbar */
  .navbar {
    background-color: #343a40 !important; /* Set navbar background color */
  }

  /* Custom CSS for navbar links */
  .navbar-nav .nav-link {
    position: relative;
    transition: border-bottom-color 0.3s ease; /* Add transition for smooth animation */
    color: #fff; /* Set navbar link color */
  }

  /* Custom CSS for navbar link hover effect */
  .navbar-nav .nav-item .nav-link:hover {
    border-bottom: 2px solid #ff4500; /* Change the border color on hover */
  }
</style>

<style>
  /* Custom CSS for navbar search button */
  .btn-search {
    border: none;
    border-color: #D2691E; /* Remove the border */
    border-radius: 24px; /* Add border-radius for rounded corners */
  }
</style>

<style>
  .btn {
    display: block;
    margin: 0 auto;
    width: 200px;
    text-align: center;
    font-size: 16px;
    padding: 5px 15px;
    border-radius: 24px;
    background-color: #D2691E; /* Less intense brown color */
    color: white;
    border: 2px solid #000;
    text-decoration: none;
    transition: background-color 0.3s ease, transform 0.2s ease;
  }
  .btn:hover {
    background-color: #A0522D; /* Darker shade of brown on hover */
    transform: scale(1.05);
  }
</style>

app/views/home/index.html.erb
<h1 style="color: #D2691E; font-family: Century Gothic;">Welcome to Guitar Tracker!</h1>
<h3 style="color: white; font-family: Century Gothic; margin-left: 0px;"> Sign Up to Get Started.</h3><br>
<p style="color: #D2691E; font-family: Century Gothic;"> - Click 'Listings' to view and add to current stored listings </p>
<p style="color: #D2691E; font-family: Century Gothic;"> - Click 'Inventory' to view and add to current stored listings </p>  

<%# List of features, how to use, how to upload images %>

app/views/home/tracker.html.erb
<h1>Tracker</h1>

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.label :brand, style: "display: block; color: #D2691E" %>
    <%= form.text_field :brand, class:"form-control", placeholder:"Brand/luthier" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :model, style: "display: block; color: #D2691E" %>
    <%= form.text_field :model, class:"form-control", placeholder:"Guitar model" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :body_type, style: "display: block; color: #D2691E" %>
    <%= form.text_field :body_type, class:"form-control", placeholder:"Body type (e.g. solid, plywood)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :wood_type, style: "display: block; color: #D2691E" %>
    <%= form.text_field :wood_type, class:"form-control", placeholder:"Wood type" %>
  </div>
  <br>
    <div class="field form-group">
    <%= form.label :finish, style: "display: block; color: #D2691E" %>
    <%= form.text_field :finish, class:"form-control", placeholder:"Finish/Colour" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :price, style: "display: block; color: #D2691E" %>
    <%= form.text_field :price, class:"form-control", placeholder:"Purchasing price" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :condition, style: "display: block; color: #D2691E" %>
    <%= form.text_field :condition, class:"form-control", placeholder:"Condition (e.g. New, Very Good, Fair/Used)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :nut_width, style: "display: block; color: #D2691E" %>
    <%= form.text_field :nut_width, class:"form-control" , placeholder:"Nut width"%>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :case_included, style: "display: block; color: #D2691E" %>
    <%= form.text_field :case_included, class:"form-control", placeholder:"Case included? (yes/no)" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :comments, style: "display: block; color: #D2691E" %>
    <%= form.text_field :comments, class:"form-control" , placeholder:"Extra comments"%>
  </div>
  <br><br>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :inventories_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit "Add to Inventory", class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div style="background-color: #343a40; border-radius: 24px; padding: 10px;"  id="<%= dom_id inventory %>">
  <p>
    <strong style="color: #D2691E;">Brand:</strong>
    <span style="color: #fff;"><%= inventory.brand %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Model:</strong>
    <span style="color: #fff;"><%= inventory.model %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Body type:</strong>
    <span style="color: #fff;"><%= inventory.body_type %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Wood type:</strong>
    <span style="color: #fff;"><%= inventory.wood_type %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Finish:</strong>
    <span style="color: #fff;"><%= inventory.finish %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Price:</strong>
    <span style="color: #fff;"><%= inventory.price %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Condition:</strong>
    <span style="color: #fff;"><%= inventory.condition %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Nut width:</strong>
    <span style="color: #fff;"><%= inventory.nut_width %></span>
  </p>

  <p style="color: #D2691E;">
    <strong>Comments:</strong>
    <span style="color: #fff;"><%= inventory.comments %></span>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1 style="color: #D2691E; font-family: Century Gothic;">Edit Guitar details</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<div class="d-flex align-items-center">
  <img src="/guitaricon.png" alt="Icon" width="150" height="150" style="vertical-align: ;">

  <h1 style="font-family: 'Century Gothic'; color: #D2691E; font-size: 28px; font-weight: bold; text-align: center; margin-bottom: 20px;
    margin-left: 20px;  text-decoration: underline;">Guitar Inventory</h1>
</div>
<table class="table table-dark table-striped" style="border-collapse: collapse; border-radius: 10px; overflow: hidden; width: 100%; background-color: gray;">
  <thead>
    <tr >
      <th>Brand</th>
      <th>Model</th>
      <th>Body</th>
      <th>Wood</th>
      <th>Finish</th>
      <th>Price</th>
      <th>Condition</th>
      <th>Nut</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <div id="inventories">
      <% @inventories.each do |inventory| %>
        <% if inventory.user == current_user %>
        <tr>
          <td><%= inventory.brand %></td>
          <td><%= inventory.model %></td>
          <td><%= inventory.body_type %></td>
          <td><%= inventory.wood_type %></td>
          <td><%= inventory.finish %></td>
          <td>£<%= inventory.price %></td>
          <td><%= inventory.condition %></td>
          <td><%= inventory.nut_width %></td>
          <td><%= inventory.comments %></td>
          <td><%= link_to "Show guitar", inventory %></td>
          <td><%= link_to "Edit", edit_inventory_path(inventory) %></td>
          <td><%= link_to 'Delete', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    </div>
  </tbody>
<br>
<%= link_to "Add to Inventory", new_inventory_path, class:"btn btn-secondary", style: "display: block; margin: 0 auto; width: 200px; text-align: center; font-size: 16px; padding: 10px 20px; border-radius: 24px; background-color: #D2691E; color: white; border-width: 0px; border-color: #D2691E; text-decoration: none; background-color: #D2691E; font-family: 'Century Gothic'" %>
<br><br>

<style>
  .btn {
    display: block;
    margin: 0 auto;
    width: 200px;
    text-align: center;
    font-size: 16px;
    padding: 5px 15px;
    border-radius: 24px;
    background-color: #D2691E; /* Less intense brown color */
    color: white;
    border: 2px solid #000;
    text-decoration: none;
    transition: background-color 0.3s ease, transform 0.2s ease;
  }
  .btn:hover {
    background-color: #A0522D; /* Darker shade of brown on hover */
    transform: scale(1.05);
  }
</style>

app/views/inventories/new.html.erb
<br>
<h1 style="color: #D2691E; font-family: Century Gothic;"><u>Add Guitar to Inventory:</u></h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to Inventory", inventories_path %>
</div>

app/views/inventories/show.html.erb
<%= render @inventory %>

<div>
  <br>
  <%= link_to "Edit Guitar", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to Inventory", inventories_path %>

  <%= button_to "Delete this Guitar", @inventory, method: :delete %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Guitar Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body  style="background-color: #202421;"">
    <%= render 'home/header'%>
    <div class="container">

    <br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>